### ISSUE TITLE
cant compile with v-backend wasm or js_browser

### ISSUE THREAD

**Issue by ibinshoid** [pisaiah/ui#17]
```
import iui as ui

fn main() {
     println("a")
}
```

This litle test program compiles and runs fine with:
`v test.v`

But when i want to compile for browser i get this:
`v -b wasm test.v`
```
.local/v/vlib/gg/gg.js.v:35:12: error: cannot register struct `gg.Event`, another type with this name exists
   33 | }
   34 | 
   35 | pub struct Event {
      |            ~~~~~
   36 | pub mut:
   37 |     frame_count  u64
```
Or this:
`v -b js_browser test.v`
```
.vmodules/iui/src/graphics.v:4:1: builder error: cannot import module "sokol.sgl" (no .v files in ".local/v/vlib/sokol/sgl")
    2 | 
    3 | import gx
    4 | import sokol.sgl
      | ~~~~~~~~~~~~~~~~
    5 | import math
    6 | import gg
```
OS is linux
V is 0.4.8 b383cce
iui is 0.0.23

**Comment by pisaiah** [comment]
V's js/wasm backend currently does not seem to support graphics. Try using Emscripten & [v-emscripten-script](https://github.com/pisaiah/v-emscripten-script) for wasm.

**Comment by ibinshoid** [comment]
works, thank you.
